CREATE TABLE hiscores (
	"Overall_XP"    integer,
	"Overall_Lvl"   integer,
	"Overall_Rank"  integer,
	"Attack_XP" integer,
	"Attack_Lvl"    integer,
	"Attack_Rank"   integer,
	"Defence_XP"    integer,
	"Defence_Lvl"   integer,
	"Defence_Rank"  integer,
	"Strength_XP"   integer,
	"Strength_Lvl"  integer,
	"Strength_Rank" integer,
	"Hitpoints_XP"  integer,
	"Hitpoints_Lvl" integer,
	"Hitpoints_Rank"    integer,
	"Ranged_XP" integer,
	"Ranged_Lvl"    integer,
	"Ranged_Rank"   integer,
	"Prayer_XP" integer,
	"Prayer_Lvl"    integer,
	"Prayer_Rank"   integer,
	"Magic_XP"  integer,
	"Magic_Lvl" integer,
	"Magic_Rank"    integer,
	"Cooking_XP"    integer,
	"Cooking_Lvl"   integer,
	"Cooking_Rank"  integer,
	"Woodcutting_XP"    integer,
	"Woodcutting_Lvl"   integer,
	"Woodcutting_Rank"  integer,
	"Fletching_XP"  integer,
	"Fletching_Lvl" integer,
	"Fletching_Rank"    integer,
	"Fishing_XP"    integer,
	"Fishing_Lvl"   integer,
	"Fishing_Rank"  integer,
	"Firemaking_XP" integer,
	"Firemaking_Lvl"    integer,
	"Firemaking_Rank"   integer,
	"Crafting_XP"   integer,
	"Crafting_Lvl"  integer,
	"Crafting_Rank" integer,
	"Smithing_XP"   integer,
	"Smithing_Lvl"  integer,
	"Smithing_Rank" integer,
	"Mining_XP" integer,
	"Mining_Lvl"    integer,
	"Mining_Rank"   integer,
	"Herblore_XP"   integer,
	"Herblore_Lvl"  integer,
	"Herblore_Rank" integer,
	"Agility_XP"    integer,
	"Agility_Lvl"   integer,
	"Agility_Rank"  integer,
	"Thieving_XP"   integer,
	"Thieving_Lvl"  integer,
	"Thieving_Rank" integer,
	"Slayer_XP" integer,
	"Slayer_Lvl"    integer,
	"Slayer_Rank"   integer,
	"Farming_XP"    integer,
	"Farming_Lvl"   integer,
	"Farming_Rank"  integer,
	"Runecrafting_XP"   integer,
	"Runecrafting_Lvl"  integer,
	"Runecrafting_Rank" integer,
	"Hunter_XP" integer,
	"Hunter_Lvl"    integer,
	"Hunter_Rank"   integer,
	"Construction_XP"   integer,
	"Construction_Lvl"  integer,
	"Construction_Rank" integer,
	"League Points_KC"  integer,
	"League Points_Rank"    integer,
	"Bounty Hunter - Hunter_KC" integer,
	"Bounty Hunter - Hunter_Rank"   integer,
	"Bounty Hunter - Rogue_KC"  integer,
	"Bounty Hunter - Rogue_Rank"    integer,
	"Clue Scrolls (all)_KC" integer,
	"Clue Scrolls (all)_Rank"   integer,
	"Clue Scrolls (beginner)_KC"    integer,
	"Clue Scrolls (beginner)_Rank"  integer,
	"Clue Scrolls (easy)_KC"    integer,
	"Clue Scrolls (easy)_Rank"  integer,
	"Clue Scrolls (medium)_KC"  integer,
	"Clue Scrolls (medium)_Rank"    integer,
	"Clue Scrolls (hard)_KC"    integer,
	"Clue Scrolls (hard)_Rank"  integer,
	"Clue Scrolls (elite)_KC"   integer,
	"Clue Scrolls (elite)_Rank" integer,
	"Clue Scrolls (master)_KC"  integer,
	"Clue Scrolls (master)_Rank"    integer,
	"LMS - Rank_KC" integer,
	"LMS - Rank_Rank"   integer,
	"PvP Arena - Rank_KC"   integer,
	"PvP Arena - Rank_Rank" integer,
	"Soul Wars Zeal_KC" integer,
	"Soul Wars Zeal_Rank"   integer,
	"Rifts closed_KC"   integer,
	"Rifts closed_Rank" integer,
	"Abyssal Sire_KC"   integer,
	"Abyssal Sire_Rank" integer,
	"Alchemical Hydra_KC"   integer,
	"Alchemical Hydra_Rank" integer,
	"Barrows Chests_KC" integer,
	"Barrows Chests_Rank"   integer,
	"Bryophyta_KC"  integer,
	"Bryophyta_Rank"    integer,
	"Callisto_KC"   integer,
	"Callisto_Rank" integer,
	"Cerberus_KC"   integer,
	"Cerberus_Rank" integer,
	"Chambers of Xeric_KC"  integer,
	"Chambers of Xeric_Rank"    integer,
	"Chambers of Xeric: Challenge Mode_KC"  integer,
	"Chambers of Xeric: Challenge Mode_Rank"    integer,
	"Chaos Elemental_KC"    integer,
	"Chaos Elemental_Rank"  integer,
	"Chaos Fanatic_KC"  integer,
	"Chaos Fanatic_Rank"    integer,
	"Commander Zilyana_KC"  integer,
	"Commander Zilyana_Rank"    integer,
	"Corporeal Beast_KC"    integer,
	"Corporeal Beast_Rank"  integer,
	"Crazy Archaeologist_KC"    integer,
	"Crazy Archaeologist_Rank"  integer,
	"Dagannoth Prime_KC"    integer,
	"Dagannoth Prime_Rank"  integer,
	"Dagannoth Rex_KC"  integer,
	"Dagannoth Rex_Rank"    integer,
	"Dagannoth Supreme_KC"  integer,
	"Dagannoth Supreme_Rank"    integer,
	"Deranged Archaeologist_KC" integer,
	"Deranged Archaeologist_Rank"   integer,
	"General Graardor_KC"   integer,
	"General Graardor_Rank" integer,
	"Giant Mole_KC" integer,
	"Giant Mole_Rank"   integer,
	"Grotesque Guardians_KC"    integer,
	"Grotesque Guardians_Rank"  integer,
	"Hespori_KC"    integer,
	"Hespori_Rank"  integer,
	"Kalphite Queen_KC" integer,
	"Kalphite Queen_Rank"   integer,
	"King Black Dragon_KC"  integer,
	"King Black Dragon_Rank"    integer,
	"Kraken_KC" integer,
	"Kraken_Rank"   integer,
	"Kree'Arra_KC"  integer,
	"Kree'Arra_Rank"    integer,
	"K'ril Tsutsaroth_KC"   integer,
	"K'ril Tsutsaroth_Rank" integer,
	"Mimic_KC"  integer,
	"Mimic_Rank"    integer,
	"Nex_KC"    integer,
	"Nex_Rank"  integer,
	"Nightmare_KC"  integer,
	"Nightmare_Rank"    integer,
	"Phosani's Nightmare_KC"    integer,
	"Phosani's Nightmare_Rank"  integer,
	"Obor_KC"   integer,
	"Obor_Rank" integer,
	"Sarachnis_KC"  integer,
	"Sarachnis_Rank"    integer,
	"Scorpia_KC"    integer,
	"Scorpia_Rank"  integer,
	"Skotizo_KC"    integer,
	"Skotizo_Rank"  integer,
	"Tempoross_KC"  integer,
	"Tempoross_Rank"    integer,
	"The Gauntlet_KC"   integer,
	"The Gauntlet_Rank" integer,
	"The Corrupted Gauntlet_KC" integer,
	"The Corrupted Gauntlet_Rank"   integer,
	"Theatre of Blood_KC"   integer,
	"Theatre of Blood_Rank" integer,
	"Theatre of Blood: Hard Mode_KC"    integer,
	"Theatre of Blood: Hard Mode_Rank"  integer,
	"Thermonuclear Smoke Devil_KC"  integer,
	"Thermonuclear Smoke Devil_Rank"    integer,
	"Tombs of Amascut_KC"   integer,
	"Tombs of Amascut_Rank" integer,
	"Tombs of Amascut: Expert Mode_KC"  integer,
	"Tombs of Amascut: Expert Mode_Rank"    integer,
	"TzKal-Zuk_KC"  integer,
	"TzKal-Zuk_Rank"    integer,
	"TzTok-Jad_KC"  integer,
	"TzTok-Jad_Rank"    integer,
	"Venenatis_KC"  integer,
	"Venenatis_Rank"    integer,
	"Vet'ion_KC"    integer,
	"Vet'ion_Rank"  integer,
	"Vorkath_KC"    integer,
	"Vorkath_Rank"  integer,
	"Wintertodt_KC" integer,
	"Wintertodt_Rank"   integer,
	"Zalcano_KC"    integer,
	"Zalcano_Rank"  integer,
	"Zulrah_KC" integer,
	"Zulrah_Rank"   integer,
	"time" timestamp,
	"player" integer
);
